name = "gr8r-revai-callback-worker"
main = "index.js"
compatibility_date = "2025-06-24"

[[r2_buckets]]
binding = "VIDEO_BUCKET"
bucket_name = "videos-gr8r"

[[services]]
binding = "SOCIALCOPY_WORKER"
service = "gr8r-socialcopy-worker"

[[services]]
binding = "GRAFANA"
service = "gr8r-grafana-worker"

[[services]]
binding = "REVAIFETCH"
service = "gr8r-revai-worker"

[[services]]
binding = "AIRTABLE"
service = "gr8r-airtable-worker"

[[services]]
binding = "ASSETS"
service = "gr8r-assets-worker"

[[routes]]
pattern = "callback.gr8r.com/*"
zone_name = "gr8r.com"
