name = "gr8r-revai-callback-worker"
main = "index.js"
compatibility_date = "2025-06-24"

[[services]]
binding = "GRAFANA"
service = "gr8r-grafana-worker"

[[services]]
binding = "REVAIFETCH"
service = "gr8r-revai-worker"

[[services]]
binding = "AIRTABLE"
service = "gr8r-airtable-worker"

[[services]]
binding = "R2"
service = "gr8r-r2-worker"

[[routes]]
pattern = "callback.gr8r.com/*"
zone_name = "gr8r.com"
